# Having a single entry point will make it easier to manage workflow
# control from the parent caller vs. directly calling each specific
# workflow.
# Why not an action?
# Maybe worthwhile looking into further, however we want to ensure
# that we are not polluting the workspace of the parent, or bloating
# the container image with additional dependencies.
name: build_FIO_for_hipFile
on:
  workflow_call:
    inputs:
      platform:
        description: "Current pipeline distro"
        required: true
        type: string
      ais_hipfile_pkg_filename:
        description: "hipFile runtime package filename"
        required: true
        type: string
      ais_hipfile_pkg_dev_filename:
        description: "hipFile development package filename"
        required: true
        type: string
    outputs:
      # Note: Only outputs matching inputs.platform will be set.
      fio_pkg_debian_filename:
        description: "FIO runtime package for Debian & downstream distros."
        value: ${{ jobs.build_FIO_suse.outputs.fio_pkg_filename }}
      fio_pkg_debian_artifact_id:
        description: "GHA Artifact ID for the Debian FIO package."
        value: ${{ jobs.build_FIO_suse.outputs.fio_pkg_artifact_id }}
      fio_pkg_fedora_filename:
        description: "FIO runtime package for Fedora & downstream distros."
        value: ${{ jobs.build_FIO_suse.outputs.fio_pkg_filename }}
      fio_pkg_fedora_artifact_id:
        description: "GHA Artifact ID for the Fedora FIO package."
        value: ${{ jobs.build_FIO_suse.outputs.fio_pkg_artifact_id }}
      fio_pkg_suse_filename:
        description: "FIO runtime package for SUSE distros."
        value: ${{ jobs.build_FIO_suse.outputs.fio_pkg_filename }}
      fio_pkg_suse_artifact_id:
        description: "GHA Artifact ID for the SUSE FIO package."
        value: ${{ jobs.build_FIO_suse.outputs.fio_pkg_artifact_id }}
permissions:
  contents: read
  packages: read
jobs:
  build_FIO_debian:
    if: ${{ inputs.platform == 'ubuntu' }}
    uses: ./.github/workflows/build-debian.yml
  build_FIO_fedora:
    if: ${{ inputs.platform == 'rocky' }}
    uses: ./.github/workflows/build-rpm.yml
  build_FIO_suse:
    if: ${{ inputs.platform == 'suse' }}
    uses: ./.github/workflows/build-rpm-suse.yml
